apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
      - args:
        - sh
        - -c
        - ./jaws.sh startfg
        image: gcr.io/esd-auto-aai-dev/master_2020-06-10_15-12-28utc:aai-install
        name: aai-server
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
